version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=StepIntoHelp;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True;
    volumes:
      - ${CERT_PATH}:/https:ro
    restart: unless-stopped

volumes:
  sqlserver_data:
