FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY ["StepIntoHelp.csproj", "./"]
RUN dotnet restore

COPY . .
RUN dotnet build

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore", "--urls", "http://0.0.0.0:5000;https://0.0.0.0:5001"]
EXPOSE 5074